[package]
name = "erm"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"]}
quick-xml = { version = "0.38", features = ["serialize"]}
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1"
